- pkgs/development/beam-modules/default.nix
> Make Elixir 1.8 default

- nixos/modules/services/backup/borgbackup.nix
I will PR this upstream if you agree. In our case, it generates a borg-job-jupiter with the following content
```sh
#! /nix/store/r47p5pzx52m3n34vdgqpk5rvqgm0m24m-bash-4.4-p23/bin/bash -e
export BORG_PASSCOMMAND='cat /root/backup-pass.txt'
export BORG_REMOTE_PATH='borg1'
export BORG_REPO='12481@ch-s012.rsync.net:./jupiter'
export BORG_RSH='ssh -i /root/id_backup'
exec "/nix/store/cs98hvqzvym1i9j31d6n6mn9xc6q0pr7-borgbackup-1.1.7/bin/borg"  "${extraFlagsArray[@]}" "$@"
```
> [OPS-511] nixos/borgbackup: generate wrappers per job for easy borg access

- nixos/modules/services/web-apps/youtrack.nix
https://issues.serokell.io/issue/OPS-728
YouTrack seems to want the `hostname` command.
Added `unixtools.hostname` to the path for the youtrack service.
Not tested.
---
> youtrack: add hostname to path

- pkgs/development/haskell-modules/configuration-nix.nix
A patch was added unconditionally that only applies to 0.15, breaking
builds of 0.14.
Apply patch only if version is 0.15.*
---
> [OPS-811] Fix servant-client-core != 0.15

- nixos/modules/module-list.nix
- nixos/modules/virtualisation/docker-containers.nix
- pkgs/applications/networking/cluster/terraform-landscape/default.nix
- pkgs/applications/networking/cluster/terraform-providers/data.nix
- pkgs/applications/networking/cluster/terraform-providers/default.nix
- pkgs/applications/networking/cluster/terraform-providers/elasticsearch/default.nix
- pkgs/applications/networking/cluster/terraform-providers/providers.txt
- pkgs/applications/networking/cluster/terraform/default.nix
Backports from `nixos-unstable-small`
Needed newer version of Terraform & Co for API compatibility.
Backported `docker-images.nix`.
> Backport Terraform packages and docker-images.nix

- nixos/modules/virtualisation/docker-containers.nix
- nixos/modules/virtualisation/docker.nix
- nixos/tests/docker.nix
I wanted a way to declaratively make sure certain named Docker volumes and networks exist.
I'm not sure I want this to try and delete networks and volumes when they are removed from the config.
Added:
* `services.docker.volumes`
* `services.docker.networks`
Tested in local VM with Agora config.
Edit: Test it yourself. Now with more NixOS tests:
```sh
$ nix-build -A nixosTests.docker
```
Changed:
`docker-containers.thecontainer = {}` was giving containers names like `docker-thecontainer.service` which is awkward when you want to use Docker's internal name resolution. Calling it simply `thecontainer` seems nicer to work with when configuring internal networking.
Cons: Requires making sure your declarative container names don't clash with any existing imperative container names on the same …
> [AG-26] Patch some Docker modules

- pkgs/servers/consul/default.nix
- pkgs/tools/security/vault/default.nix
- pkgs/tools/security/vault/vault-bin.nix
- pkgs/top-level/all-packages.nix
Import `vault-bin`, and update `vault` and `consul`.
---
> Backport from nixos-unstable-small: vault, vault-bin, consul

- pkgs/development/tools/skopeo/default.nix
`skopeo` broke after being bumped to 1.4.0, this fix is cherry-picked from https://github.com/NixOS/nixpkgs/pull/82261
> Fix skopeo

- nixos/modules/services/monitoring/prometheus/default.nix
Accessing the configured port of a service is quite useful, for example
when configuring virtual hosts for a service. The prometheus module did
not expose the configured por separately, making it unnecessarily
cumbersome to consume.
This is a breaking change only if you were setting `listenAddress` to
a non-standard value. If you were, you should now set `listenAddress`
and `port` separately.
Maybe there should be an assertion that `listenAddress` does not match `:[0-9]{1,5}$` or similar, so that failure to fix your config is reported at eval time. How does one do that?
Also, apparently GFM doesn't respect the markdown standard of ignoring single linebreaks. Now this description looks stupid.
> prometheus: Split options listenAddress and port

- nixos/modules/services/backup/borgbackup.nix
- nixos/tests/borgbackup.nix
Routinely verify repo integrity
For each defined job, define a unit and a weekly timer that checks the
associated repo.
> borgbackup: add check service

- nixos/modules/services/backup/borgbackup.nix
Otherwise it says:
Failed to add dependency on borgbackup-job-albali, ignoring: Invalid argument
> borgbackup: Specify dependencies correctly

- nixos/modules/services/security/oauth2_proxy_nginx.nix
Cherry-picked from https://github.com/NixOS/nixpkgs/pull/112391.
Fixes the issue when signing in at one domain redirects you to a different domain.
> [OPS-1156] nixos/oauth2_proxy_nginx: specify hostname in X-Auth-Request-Redirect

- pkgs/applications/networking/cluster/terraform/default.nix
tezos-infra needs the newer version
> [OPS-1169] Bump terraform 0_13 to 0.13.6

- pkgs/build-support/setup-hooks/reproducible-builds.sh
This fix is required for https://github.com/serokell/tezos-packaging, otherwise, reference cycles occur there
> stdenv: trim random seed to avoid reference cycles

- pkgs/build-support/setup-hooks/reproducible-builds.sh
This reverts commit 93c23a92ad7ff55b5c12004f73eeffc7724a0e03.
Cherry pick of 93c23a92ad7ff55b5c12004f73eeffc7724a0e03 causes massive cache misses:(
> Revert "stdenv: trim random seed to avoid reference cycles"

- nixos/modules/virtualisation/oci-containers.nix
Packages are coercible to string, and strings allow to set explicit paths, such
as closures deployed separately from the system profile.
> oci-containers: allow imageFile to be a path rather than package

- nixos/modules/services/continuous-integration/buildkite-agents.nix
- nixos/tests/buildkite-agents.nix
This is a fairly naive implementation, in accordance to the official docs: https://buildkite.com/docs/tutorials/parallel-builds#running-multiple-agents
You can specify a `count` option for an agent, and it will just create additional systemd units. Same user, same state folder, etc. Buildkite swear this is fine, but obviously we need to take care that tests that can run at the same time don't also try to use the same database at the same time and such.
> [OPS-1102] buildkite agent concurrency

- pkgs/applications/version-management/danger-gitlab/Gemfile
- pkgs/applications/version-management/danger-gitlab/Gemfile.lock
- pkgs/applications/version-management/danger-gitlab/default.nix
- pkgs/applications/version-management/danger-gitlab/gemset.nix
- pkgs/top-level/all-packages.nix
`danger` automates some checks for PRs https://danger.systems/ruby/, and `danger-gitlab` is a wrapper gem which includes `gitlab` package to make it work for gitlab MRs. Morley devs want to try it: https://issues.serokell.io/issue/TM-568
> [TM-568] danger-gitlab: init at 8.0.0

- pkgs/servers/jetbrains/youtrack.nix
Fixes YouTrack, cherry-picked from https://github.com/NixOS/nixpkgs/pull/138124
> [OPS-1269] youtrack: switch to jdk11 to fix the service

- nixos/modules/services/misc/nix-daemon.nix
checkConfig = false used to trigger on nix 2.3
- [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
- or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
- made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release- …
> nix.conf: disable config checks on "checkConfig = false"

- nixos/modules/virtualisation/docker.nix
- nixos/tests/docker.nix
This reverts commit 4f5445aa6317f5f1aa67cecc35cd5c6207f50f9b.
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
- or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
- made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant …
> Revert "docker.nix: Add options for named volumes and networks"

- pkgs/tools/package-management/copr-cli/default.nix
Problem: 'copr-cli' fails with 'ModuleNotFoundError: No module named 'pkg_resources'' in runtime.
Solution: Add 'setuptools' to 'propagatedBuildInputs'.
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
- or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
- made sure NixOS …
> copr-cli: fix build configuration
